language: python
python:
  - "3.6"


# Glpk solver must be install though apt, as it is not a python package  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y glpk-utils

# Install python dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - pytest ./tests/unit
